[metadata]
version = 0
name = "Default"
type = "resources"

[[sprites]]
name = "BG_Grasslands"
file = "Assets/Sprite/BG_Grasslands.toml"

[[sprites]]
name = "BG_Temple"
file = "Assets/Sprite/BG_Temple.toml"

[[sprites]]
name = "RemainTime"
file = "Assets/Sprite/RemainTime.toml"

[[sprites]]
name = "Score"
file = "Assets/Sprite/Score.toml"

[[sprites]]
name = "UI_Arrow"
file = "Assets/Sprite/UI_Arrow.toml"

[[sprites]]
name = "UI_EndGame"
file = "Assets/Sprite/UI_EndGame.toml"

[[sprites]]
name = "Floor"
file = "Assets/Sprite/Floor.toml"

[[sprites]]
name = "hollow_knight"
file = "Assets/Sprite/hollow_knight.sprite.toml"

[[sprites]]
name = "Pixel_Hero"
file = "Assets/Sprite/Pixel_Hero.sprite.toml"

[[sprites]]
name = "Pixel_Hero-Bow"
file = "Assets/Sprite/Pixel_Hero-Bow.sprite.toml"

[[sprites]]
name = "Torch"
file = "Assets/Sprite/Torch.toml"

[[sprites]]
name = "Bush"
file = "Assets/Sprite/Bush.toml"

[[sprites]]
name = "MetalBox"
file = "Assets/Sprite/MetalBox.toml"

[[sprites]]
name = "Basic_Arrow"
file = "Assets/Sprite/Basic_Arrow.toml"

[[sprites]]
name = "Fire"
file = "Assets/Sprite/Fire.sprite.toml"