[metadata]
version = 0
name = "Default"
type = "resources"

[[sprites]]
name = "BG_Grasslands"
file = "Assets/Sprite/BG_Grasslands.toml"

[[sprites]]
name = "hollow_knight"
file = "Assets/Sprite/hollow_knight.sprite.toml"

[[sprites]]
name = "Pixel_Hero"
file = "Assets/Sprite/Pixel_Hero.sprite.toml"

[[sprites]]
name = "Pixel_Hero-Bow"
file = "Assets/Sprite/Pixel_Hero-Bow.sprite.toml"

[[sprites]]
name = "Torch"
file = "Assets/Sprite/Torch.toml"

[[sprites]]
name = "Bush"
file = "Assets/Sprite/Bush.toml"

[[sprites]]
name = "Basic_Arrow"
file = "Assets/Sprite/Basic_Arrow.toml"

[[sprites]]
name = "Fire"
file = "Assets/Sprite/Fire.sprite.toml"