[metadata]
version = 0
name = "Fire"
type = "sprite"

[sheet]
image = "Assets/Sprite/Fire.png"
rows = 7
columns = 7

[[animations]]
name = "idle"
start_row = 0
start_col = 0
frame_count = 49
frame_duration_ms = 160
