[metadata]
version = 0
name = "hollow_knight"
type = "sprite"

[sheet]
image = "Assets/Sprite/hollow_knight.png"
rows = 16
columns = 16

[[animations]]
name = "walk"
start_row = 0
start_col = 0
frame_count = 8
frame_duration_ms = 160
