[metadata]
version = 0
name = "hollow_knight"
type = "sprite"

[[images]]
path = "Assets/Sprite/hollow_knight.png"

# Declaration Order is Frame Order
[[frames]]
image_index = 0
offset      = [  0,   0]
pixel_size  = [128, 128]
# pivot range is 0.0~1.0 at w, h
# default is center
# pivot = [0.5, 0.5]
[[frames]]
image_index = 0
offset      = [128,   0]
pixel_size  = [128, 128]
[[frames]]
image_index = 0
offset      = [256,   0]
pixel_size  = [128, 128]
[[frames]]
image_index = 0
offset      = [384,   0]
pixel_size  = [128, 128]
[[frames]]
image_index = 0
offset      = [384,   0]
pixel_size  = [128, 128]

[[frames]]
image_index = 0
offset      = [512,   0]
pixel_size  = [128, 128]
[[frames]]
image_index = 0
offset      = [640,   0]
pixel_size  = [128, 128]
[[frames]]
image_index = 0
offset      = [768,   0]
pixel_size  = [128, 128]

[[animations]]
name   = "idle"
frames = [0]
frame_duration_ms = 0

[[animations]]
name   = "walk"
frames = [0, 1, 2, 3, 4, 5, 6, 7]
frame_duration_ms = 160
