[metadata]
version = 0
name = "Pixel_Hero-Bows"
type = "sprite"

[sheet]
image = "Assets/Sprite/Pixel_Hero-Bow.png"
rows = 1
columns = 6

[[animations]]
name = "idle"
start_row = 0
start_col = 0
frame_count = 1
frame_duration_ms = 160
