[metadata]
version = 0
name = "Attack"
type = "sprite"

[sheet]
image = "Assets/Sprite/Pixel_Hero-Bow-Attack.png"
rows = 1
columns = 6

[[animations]]
name = "Attack"
start_row = 0
start_col = 0
frame_count = 6
frame_duration_ms = 160
