[metadata]
version = 0
name = "Default"
type = "app"

[runtime]
app_name = "SmolApp"
app_version = "v1.0.0"
app_identifier = "io.github.pulnip.smol"

[runtime.window]
title = "SmolApp"
width = 800
height = 600
fullscreen = false
resizable = false
borderless = false
always_on_top = false

[project]
content_root = "Content/"

[boot]
resource_manifest = "Default.resource.toml"
prefab_manifest = "Default.prefab.toml"
default_input = "Input/Default.input.toml"
startup_scene = "Scene/Default.scene.toml"
