[metadata]
version = 0
name = "Example"
type = "scene"

[[actors]]
type = "CharacterController"
name = "PlayerController"
[[actors.components]]
type = "InputComponent"

[[actors]]
type = "PlayerCharacter"
position = [5, 3, 0]
name = "Player"
possessed_by = "PlayerController"
[[actors.components]]
type = "SpriteAnimComponent"
sprite = "Assets/Sprite/Pixel_Hero-Idle.sprite.toml"
sprite_scale = [8, 8]
[[actors.components]]
type = "MoveComponent"
speed = 16
scale = 5.0
[[actors.components]]
type = "ColliderComponent"
scale = [3, 7]
layer = 0b1
mask = 0b1
[[actors.components]]
type = "BowComponent"
[[actors.components]]
type = "LineRenderer"

[[actors]]
type = "Actor"
position = [-2, 5, 0]
name = "NPC"
[[actors.components]]
type = "SpriteComponent"
sprite = "Assets/Sprite/Pixel_Hero-Idle.sprite.toml"
sprite_scale = [8, 8]

[[actors]]
type = "ArrowActor"
position = [0, 0, 0]
name = "ElementalActor"
[[actors.components]]
type = "SpriteComponent"
sprite = "Assets/Sprite/Basic_Arrow.toml"
sprite_scale = [3, 3]
[[actors.components]]
type = "ColliderComponent"
scale = [3, 3]
layer = 0b1
mask = 0b1
[[actors.components]]
type = "ElementalComponent"

[[actors]]
type = "FireActor"
position = [0, 0, 0]
name = "FireActor1"
[[actors.components]]
type = "SpriteComponent"
sprite = "Assets/Sprite/Fire.sprite.toml"
image_path = "Assets/Sprite/Fire.png"
sprite_scale = [1, 1]
[[actors.components]]
type = "ColliderComponent"
scale = [1, 1]
layer = 0b1
mask = 0b1
[[actors.components]]
type = "ElementalComponent"