[metadata]
version = 0
name = "Example"
type = "scene"

[[actors]]
type = "Actor"
position = [0, 0, 0]
name = "BackGround"
[[actors.components]]
type = "SpriteComponent"
sprite = "BG_Temple"
sprite_scale = [50, 28]

[[actors]]
type = "GameManager"
name = "GameManager"

[[actors]]
type = "Actor"
position = [-0.5, 12.5, 0]
name = "RemainTimeUIBackGround"
[[actors.components]]
type = "SpriteComponent"
sprite = "RemainTime"
sprite_scale = [7, 3]

[[actors]]
type = "Actor"
position = [-11.5, 12.5, 0]
name = "ScoreUIBackGround"
[[actors.components]]
type = "SpriteComponent"
sprite = "Score"
sprite_scale = [7, 3]

[[actors]]
type = "Actor"
position = [-20.9, 12.5, 0]
name = "ArrowUIBackGround"
[[actors.components]]
type = "SpriteComponent"
sprite = "Score"
sprite_scale = [7, 3]

[[actors]]
type = "Actor"
position = [-23.3, 12.5, 0]
name = "ArrowUIIcon"
[[actors.components]]
type = "SpriteComponent"
sprite = "UI_Arrow"
sprite_scale = [3, 3]

[[actors]]
type = "Actor"
position = [0, 0, 0]
name = "UI_EndGame"
[[actors.components]]
type = "SpriteComponent"
sprite = "UI_EndGame"
sprite_scale = [1, 1]

[[actors]]
type = "Actor"
position = [-20.4, -13.3, 0]
name = "Floor"
[[actors.components]]
type = "SpriteComponent"
sprite = "Floor"
sprite_scale = [7, 3]

[[actors]]
type = "CharacterController"
name = "PlayerController"
[[actors.components]]
type = "InputComponent"

[[actors]]
type = "PlayerCharacter"
position = [-20, -10, 0]
name = "Player"
possessed_by = "PlayerController"
[[actors.components]]
type = "SpriteAnimComponent"
sprite = "Pixel_Hero"
sprite_scale = [5, 5]
[[actors.components]]
type = "MoveComponent"
speed = 16
scale = 5.0
# [[actors.components]]
# type = "ColliderComponent"
# scale = [3, 7]
# layer = 0b1
# mask = 0b1
[[actors.components]]
type = "BowComponent"
[[actors.components]]
type = "LineRenderer"

[[actors]]
type = "TochLitActor"
position = [-10, 15, 0]
name = "TochLitActor1"

[[actors]]
type = "TochLitActor"
position = [0, 15, 0]
name = "TochLitActor2"

[[actors]]
type = "BushActorSpawner"
position = [14, 11, 1]
name = "BushActorSpawner1"

[[actors]]
type = "BushActorSpawner"
position = [14, 6, 1]
name = "BushActorSpawner2"

[[actors]]
type = "BushActorSpawner"
position = [14, 1, 1]
name = "BushActorSpawner3"

[[actors]]
type = "BushActorSpawner"
position = [14, -4, 1]
name = "BushActorSpawner4"

[[actors]]
type = "BushActorSpawner"
position = [14, -9, 1]
name = "BushActorSpawner5"