[metadata]
version = 0
name = "EngineTest"
type = "scene"

[[actors]]
prefab = "DefaultController"
name = "PlayerController"

[[actors]]
prefab = "ExampleActor"
name = "Player"

[[actors]]
prefab = "NPC"
name = "NPC1"
position = [-12, 5, 0]
[[actors.components]]
debugFlag = false

[[actors]]
prefab = "NPC"
name = "NPC2"
position = [12, 3, 0]

[[actor]]
type = "Actor"
name = "NPC3"
position = [-1, -8, 0]
[[actor.components]]
type = "SpriteComponent"
name = "hollow_knight"
sprite_scale = [8, 8]
[[actor.components]]
type = "ColliderComponent"
scale = [3, 7]
layer = 0b1
mask = 0b0
