[metadata]
version = 0
name = "Example"
type = "scene"

[[actors]]
type = "CharacterController"
name = "PlayerController"
[[actors.components]]
type = "InputComponent"

[[actors]]
type = "ExampleActor"
name = "Player"
possessed_by = "PlayerController"
[[actors.components]]
type = "SpriteComponent"
image_path = "Assets/Sprite/hollow_knight.png"
